apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: docker-sample
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-sample
  template:
    metadata:
      labels:
        app: docker-sample
    spec:
      containers:
      - name: app
        image: docker-sample:0.0.1
