apiVersion: v1
kind: Service
metadata:
  name: docker-sample-service
  namespace: test
spec:
  selector:
    app: docker-sample
    version: v1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      name: non-secure
      targetPort: web
      nodePort: 30445

