apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-sample-deployment
  namespace: test
spec:
  replicas: 4
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: docker-sample
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: docker-sample
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: app
        image: docker-sample:0.0.1
        ports:
        - containerPort: 8080
        - containerPort: 8090
        env:
        - name: TZ
          value: Asia/Tehran
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
